version: '3.3'
services:
    php-fpm:
        image: php:fpm-alpine
        ports:
            - 9000:9000
        volumes:
            - ./public:/var/www/some-site/html
    nginx:
        image: nginx:alpine
        ports:
            - 4567:80
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php-fpm
volumes:
    public:
